# Generated by Django 3.0.2 on 2020-07-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_kidsdream_kidsdreamtextslider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kidsdreamtextslider',
            old_name='kide_dream',
            new_name='kids_dream',
        ),
    ]
