# Generated by Django 3.0.2 on 2020-07-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_donateslider_donateslidertext_donatetext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatetext',
            old_name='donte_text',
            new_name='donate_text',
        ),
    ]
